In [6]:
import pandas as pd

In [7]:
s1 = pd.Series([1,1,2,3,4])
s1

0    1
1    1
2    2
3    3
4    4
dtype: int64

In [8]:
s1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
data = {101:"Junaid",102:"Seema",103:"Rahul",104:"Tarun"}
s1 = pd.Series(data)
s1

101    Junaid
102     Seema
103     Rahul
104     Tarun
dtype: object

In [10]:
import numpy as np
s1 = pd.Series(50,index = np.arange(1,11))
s1

1     50
2     50
3     50
4     50
5     50
6     50
7     50
8     50
9     50
10    50
dtype: int64

In [11]:
s1 = pd.Series(np.arange(1,11))
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [12]:
s1[0]

np.int64(1)

In [13]:
s1[2:6]

2    3
3    4
4    5
5    6
dtype: int64

In [14]:
s1[3:-3]

3    4
4    5
5    6
6    7
dtype: int64

In [15]:
s1[[2,5,7]]

2    3
5    6
7    8
dtype: int64

In [16]:
s1[0]=22

In [17]:
s1

0    22
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [18]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [19]:
s1.add(5)

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
9    15
dtype: int64

In [20]:
s1.iloc[3]

np.int64(4)

In [21]:
data = {101:"Junaid",102:"Seema",103:"Rahul",104:"Tarun"}
s1 = pd.Series(data)
print(s1.iloc[3])
print(s1.loc[101])

Tarun
Junaid

In [22]:
s1.iloc[0]

'Junaid'

In [23]:
s1.loc[101]

'Junaid'